<!-- try/catch/finally構文の例 -->
<script>
    try {
        nonExistingFunction(); //存在しない関数
        console.log("例外により実行されません。");
    } catch (error) {
        console.error("例外が発生しました。");
        console.error("エラータイプ：" + error.name);
        console.error("エラーメッセージ：" + error.message);
    } finally {
        console.log("後処理の記述が必要な場合はここに記述します。");
    }

    console.log("例外が発生しても後続のコードが実行されます。");

    // >例外が発生しました。
    // >エラータイプ：ReferenceError
    // >エラーメッセージ：nonExistingFunction is not defined
    // >後処理の記述が必要な場合はここに記述します。
    // >例外が発生しても後続のコードが実行されます。
</script>
