<script>
    try {
        let b = 10 + a;
        console.log(b);

    } catch (error) {
        console.error(error.name);
        console.error(error.message);
        
    } finally {
        console.log("後続の処理");
    }
</script>